### PR TITLE
Fix/215

### LINKED ISSUE #212: add pdf extension on windows in export pdf

### PR DESCRIPTION
**Pull request by DeanVerjans**
fix #212 #215

### CODE REVIEW

File: app/containers/App.js [hunk 1]
```diff
@@ -23,20 +24,21 @@ const iconStyle = {
   marginRight: 20
 }
 
-class App extends Component {
-  constructor (props) {
-    super(props)
-    this.state = {}
+const mapStateToProps = state => {
+  console.log(state)
```
Comment (DylanVerstraete) [inline app/containers/App.js]: remove this console.log please

File: app/containers/App.js [hunk 2]
```diff
@@ -23,20 +24,21 @@ const iconStyle = {
...
+class App extends Component {
   handleItemClick = (e, { name }) => {
-    this.setState({ activeItem: routes[name] })
     this.props.history.push(routes[name])
   }
 
   render () {
-    const { children } = this.props
-    const { activeItem } = this.state
+    console.log(this.props)
```
Comment (DylanVerstraete) [inline app/containers/App.js]: remove this console.log please

**Comment by DylanVerstraete** [comment]
:ship: LGTM :ship: 🐰
